language: python

python:
  - "3.6"

cache: pip

install:
  - pip install flake8
  - pip install flake8-docstrings
  - pip install -e .

script: 
  - flake8
  - pytest

branches:
  only:
    - master

notifications:
  slack: jbloomlab:M5Ap209HwoU6g0ECE137npd5
