language: python

python:
  - "3.6"

cache: pip

install:
  - > 
     pip install
     flake8
     flake8-docstrings
     flake8-rst-docstrings
     flake8-builtins
     flake8-import-order
  - pip install -e .

script: 
  - flake8
  - pytest

branches:
  only:
    - master

notifications:
  slack: jbloomlab:M5Ap209HwoU6g0ECE137npd5
